- pkg/mmesh/etcd_secret.go
- scripts/install.sh
This reverts commit 564e71b6ccc2da7c29442fb6efbb1d04b6368ce4.
This will allow runtime detection of the namespace where modelmesh-serving is installed
Reverts upstream change that was in favor of install script sed to replace the namespace
The namespace of modelmesh-serving will be determined at runtime
> Revert "Fix etcd endpoints when etcd is in different namespace (#188)"

- quickstart/quickstart.sh
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Wait for CRDS to be created in quickstart script

- tests/Dockerfile
We took Pipfile and Pipfile.lock files out because we didn't need them for modelmesh tests. Taking references to these files out from the Dockerfile, as the DockerBuild is failing in CI: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/32617/rehearse-32617-pull-ci-opendatahub-io-modelmesh-serving-main-modelmesh-serving-e2e/1574792991636197376
> Removing Pipfile and Pipfile.lock references

- tests/Dockerfile
Removing micropipenv install as we don't need it, and it's causing the DockerBuild to fail in CI: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/32617/rehearse-32617-pull-ci-opendatahub-io-modelmesh-serving-main-modelmesh-serving-e2e/1574820789461454848/build-log.txt
```
Failed to find Pipfile.lock or poetry.lock or requirements.txt in the current directory or any of its parent: '/root/peak'
error: build error: error building at STEP "RUN pip3 install micropipenv &&    ln -s `which pip3` /usr/bin/pip &&    cd $HOME/peak &&    micropipenv install": error while running runtime: exit status 3
```
> Removing micropipenv install

- odh-model-controller/config/rbac/role.yaml
- odh-model-controller/controllers/inferenceservice_route.go
- quickstart/triton.yaml
Any inference services created with `create-route: "True"` as an annotation will have routes created for them.
If this annotation is removed, the route will be deleted.
If this annotation never existed, the route will not be created at all.
Image to be used: quay.io/anishasthana/odh-model-controller-test:v3
> Allow users to manually specify creation of routes

- manifests/opendatahub/dependencies/fvt.yaml
- manifests/opendatahub/dependencies/quickstart.yaml
Tested out on a cluster and pods come up as expected, without any issues.
Closes [RHODS-5438](https://issues.redhat.com/browse/RHODS-5438)
> Adding Probes to ModelMesh Serving pods

- tests/scripts/install.sh
CI tests failing due to incorrect URI specified in the sed: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/opendatahub-io_modelmesh-serving/25/pull-ci-opendatahub-io-modelmesh-serving-main-modelmesh-serving-e2e/1587150969056006144
> Fix: Fix sed for kfdef URI / CI test failure

- manifests/opendatahub/dependencies/quickstart.yaml
Even though in their respective manifests etcd service selects on label `app: etcd` this is overwritten by this kustomization [setting](https://github.com/red-hat-data-services/modelmesh-serving/blob/main/manifests/opendatahub/base/kustomization.yaml#L4). 
The result is the etcd service selects on all pods with the label `app: model-mesh`, this is a workaround change that will ensure etcd service only selects on etcd pods. A more robust solution would re organize the labels, and not add a broad `app: modelmesh` label on _all resources_ if the plan is to select on these labels by component.
> Have etcd service select only etcd pods.

- manifests/opendatahub/runtimes/kustomization.yaml
Effort to sync upstream manifests 
Ref: https://issues.redhat.com/browse/RHODS-6136
The updated openvino newTag will now match with the one in: https://github.com/opendatahub-io/odh-manifests/blob/master/model-mesh/runtimes/kustomization.yaml
This is the only difference between the manifests within upstream modelmesh repos
Signed-off-by: Selbi <43946617+heyselbi@users.noreply.github.com>
> Update newTag to match the one in odh-manifests

- controllers/testdata/servingruntime_controller_upstream.golden
**Description**
The test data is updated.
**JIRA:** https://issues.redhat.com/browse/RHODS-6132
**Test way:** 
- clone the repository
- execute `make run test` cmd
**Expected message:**
~~~
?   	github.com/kserve/modelmesh-serving	[no test files]
ok  	github.com/kserve/modelmesh-serving/apis/serving/v1alpha1	0.045s	coverage: 1.8% of statements
ok  	github.com/kserve/modelmesh-serving/controllers	14.502s	coverage: 16.4% of statements
ok  	github.com/kserve/modelmesh-serving/controllers/config	0.048s	coverage: 33.0% of statements
ok  	github.com/kserve/modelmesh-serving/controllers/modelmesh	0.041s	coverage: 44.1% of statements
?   	github.com/kserve/modelmesh-serving/generated/mmesh	[no test files]
ok  	github.com/kserve/modelmesh-serving/pkg/config	0.038s	coverage: 49.6% of statements
ok …
> Fix unit test for odh

- Makefile
- config/dependencies/fvt.yaml
- fvt/fvtclient.go
- Upstream modelmesh fvt test is not running with odh-modelmesh.
- Moreover, odh-modelmesh need to add this fvt test to openshift-ci as E2E test to check every PR validation.
- Add openshift-ci make targets
- Increase timeout for ISVC deployment from 120s to 600s 
- Change ETCD image from coreos to registry.access.redhat.com. 
- Still, the image can be pulled without credential
- Change --data-dir of etcd in order to avoid permission issues.  
After you login to Openshift cluster, execute the following commands:
~~~
NAMESPACE=modelmesh-serving make e2e-test
~~~
~~~
...
Ran 5 of 5 Specs in 79.927 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 2 suites in 4m26.116938102s
Test Suite Passed
~~~
> Fix e2e test and add openshift-ci make target

- manifests/opendatahub/dependencies/quickstart.yaml
- quickstart/quickstart.sh
As a part of adding model-mesh to ODH, we should not have users need to apply any commands manually to deploy models using ODH. Currently the etcd secrets are created by the quickstart.sh which is not compatible with wanting a one-click deployment using a ODH kfdef. In the interest of keeping the manifests in opendatahub-io/odh-manifests and the manifests in opendatahub-io/modelmesh-serving/manifests in sync, the same change is being replicated here. 
Add initContainers to the etcd deployment, along with the rbac needed to generate secrets without user intervention
- In a fresh cluster, install the OpenDataHub operator
- `cd quickstart`
- edit `manifests/kfdef.yaml` as follows `repos:name:manifests` -> `uri:  https://api.github.com/repos/VedantMahabaleshwarkar/modelmesh-serving/tarball/etc …
> Create etcd secrets inside initContainer

- Dockerfile.develop
In order to use this dockerfile.develop as a root image in the openshift ci, it needs findutils.
> add findutils package for openshift ci

- Makefile
- fvt/globals.go
- scripts/install.sh
KServe [develop guide doc](https://github.com/kserve/modelmesh-serving/blob/main/docs/developer.md) provides how to deploy a custom modelmesh serving  image.
~~~
kubectl set image deployment/modelmesh-controller manager=localhost:5000/modelmesh-controller:latest
~~~
This manual step is a little  huddle when I try to install the custom image so I add an option `modelmesh-serving-image` in install.sh to accept image url. The option will automatically update the image information.
install.sh file 
- Add `--modelmesh-serving-image`
This script will deploy ${MODELMESH_SERVING_IMAGE}. If it is not set, the default image will be deployed.
```
./scripts/install.sh --namespace ${NAMESPACE} --install-config-path config --dev-mode-logging --fvt --modelmesh-serving-image ${MODELMESH_SERVING_IMAGE} …
```
> add modelmesh-serving-image option to accept a custom image url

- config/default/config-defaults.yaml
- config/internal/base/deployment.yaml.tmpl
- config/rbac/common/kustomization.yaml
- config/rbac/common/modelmesh-serving-service-account.yaml
JIRA: [RHODS-7319](https://issues.redhat.com/browse/RHODS-7319)
- Create a sa "modelmesh-serving-sa'
- Default config specified this new sa as a default SA
- Update Deployment.yaml.tmpl to pick SA dynamically.
~~~
oc login
git clone --branch update-sa https://github.com/Jooho/modelmesh-serving.git
cd modelmesh-serving
TAG=20230221-1
NAMESPACE=modelmesh-serving MODELMESH_SERVING_IMAGE=quay.io/jooholee/modelmesh-controller:${TAG} make deploy-release-dev-mode-fvt
cat <<EOF |oc create -f -
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
name: example-sklearn-isvc
annotations:
serving.kserve.io/deploymentMode: ModelMesh
spec:
predictor:
model:
modelFormat:
name: sklearn
storage:
key: localMinIO
path: sklearn/mnist-svm.joblib
EOF
~~~
~~~
oc get pod
NAME …
> create modelmesh-serving-sa and update oauth-proxy deployment 

- controllers/testdata/test-config-defaults.yaml
This is about test data for unit test. 
Previously, it does not include serviceAccountName because it was hard-coded. However, it is not dynamic and it can be overrided by #74
> Update test-data for unit test about sa

- config/internal/base/deployment.yaml.tmpl
- controllers/testdata/servingruntime_controller.golden
- controllers/testdata/test-config-payload-processor-error.yaml
- controllers/testdata/test-config-payload-processor.yaml
The tmpl file does not set {{.ServiceAccountName}}. It required double-quote so I added it.
Plus I updated payload test config to use the right serviceaccount.
~~~
make run test
~~~
~~~
go test -coverprofile cover.out `go list ./... | grep -v fvt`
?       github.com/kserve/modelmesh-serving     [no test files]
ok      github.com/kserve/modelmesh-serving/apis/serving/v1alpha1       0.059s  coverage: 1.8% of statements
ok      github.com/kserve/modelmesh-serving/controllers 14.623s coverage: 17.2% of statements
ok      github.com/kserve/modelmesh-serving/controllers/config  0.015s  coverage: 33.0% of statements
ok      github.com/kserve/modelmesh-serving/controllers/modelmesh       0.021s  coverage: 44.0% of statements
?       github.com/kserve/modelmesh-serving/generated/mmesh     [no test …
> update test config yaml to use the right servingaccount

- config/internal/base/deployment.yaml.tmpl
This added MM parameter `MM_PAYLOAD_PROCESSORS` for trustAI. 
~~~
NAMESPACE=modelmesh-serving make e2e-test
~~~
~~~
Ran 5 of 5 Specs in 79.927 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 2 suites in 4m26.116938102s
Test Suite Passed
~~~
> add trustAI processor into tmpl file

- Dockerfile
- config/internal/base/deployment.yaml.tmpl
- controllers/testdata/servingruntime_controller.golden
- controllers/testdata/test-config-payload-processor-error.yaml
- controllers/testdata/test-config-payload-processor.yaml
- version
- This is the last commit to sync upstram kserve/modelmesh 0.11.0-alpha version.
- Added version file 
- Unit test changed
Master passed all openshift ci (unit test/fvt test) and it is already merged.
This PR is like cherry pick so it should be no differences this branch with master branch.
~~~
NAMESPACE=modelmesh-serving make e2e-test
~~~
~~~
Ran 5 of 5 Specs in 79.927 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
Ginkgo ran 2 suites in 4m26.116938102s
Test Suite Passed
~~~
> Sync with master and add version for 0.11.0-alpha branch

- .gitignore
- opendatahub/scripts/deploy_fvt.sh
- opendatahub/scripts/env.sh
- opendatahub/scripts/install_odh.sh
Scripts for a quick start is not using dockerfile.develop container so it needs to download the required binaries.
Adding downloading binaries logic.
It downloads
- kfctl
- kustomize
- yq
into ./bin folder.
- [V] Unit tests pass locally
- [V] FVT tests pass locally
- [V] Tested modelmesh serving deployment with odh-manifests and ran odh-manifests-e2e tests locally
> Add downloading required binaries logic 

- opendatahub/docs/get-started-odh-modelserving.md
- opendatahub/quickstart/README.md
- opendatahub/quickstart/basic/README.md
- opendatahub/quickstart/common_docs/modelmesh-cleanup.md
- opendatahub/quickstart/common_docs/modelmesh-install.md
- opendatahub/quickstart/hpa/README.md
- opendatahub/quickstart/pvc/README.md
Copy edit requested by development
Multiple updates to the readme files
> doc-review-qs copy edit of quick starts for ModelMesh

- README.md
In main README, the link to the quickstart guide goes to the upstream instructions that does not work for ODH:
The link is fixed to point to the right quickstart guide.
> Fix quickstart link in /README.md

- README.md
> Fix quick start link to go to the root of quick starts

- main.go
Modelmesh Controller has a memory leak issue(https://issues.redhat.com/browse/RHODS-8868) so it needs to gather heapdump. In order to get detailed data, `net/http/pprof` package should be added.
This change will deploy a webserver and it provides to download data but this web server requires authentication to download debugging data.
Main branch - https://github.com/opendatahub-io/modelmesh-serving/pull/102
Added pprof package.
Add `ENABLE_PPROF` environmental variable in the odh-modelmesh-controller deployment.
~~~
oc port-forward pod/modelmesh-controller-XXXX  9999:9999
http://localhost:9999/debug/pprof/heap
~~~
~~~
heap file will be downloaded.
~~~
Checklist items below are applicable …
> [Cherry-Pick]Add Profiling feature to get debug data for modelmesh controller.

- main.go
Modelmesh Controller has a memory leak issue(https://issues.redhat.com/browse/RHODS-8868) so it needs to gather heapdump. In order to get detailed data, `net/http/pprof` package should be added.
This change will deploy a webserver and it provides to download data but this web server requires authentication to download debugging data.
Added pprof package.
Add `ENABLE_PPROF` environmental variable in the odh-modelmesh-controller deployment.
~~~
oc port-forward pod/modelmesh-controller-XXXX  9999:9999
http://localhost:9999/debug/pprof/heap
~~~
~~~
heap file will be downloaded.
~~~
> Add Profiling feature to get debug data for modelmesh controller.

- opendatahub/docs/generate-manifests.md
- opendatahub/odh-manifests/model-mesh_templates_stable/OWNERS
- opendatahub/odh-manifests/model-mesh_templates_stable/README.md
- opendatahub/odh-manifests/model-mesh_templates_stable/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/base/params.env
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-model-controller/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-model-controller/overlays/odh/params.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/manager/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/manager/service.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/params.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/quickstart.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/rbac/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/rbac/networkpolicy_etcd.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/rbac/remove_networkpolicy_rumtime_patch.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/rbac/role_apps_metrics_access.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/rbac/user_cluster_roles.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/scripts/enable_auth.sh
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/scripts/kustomization.yaml
- opendatahub/scripts/gen-manifests/odh_model_manifests.sh
- opendatahub/scripts/gen-manifests/odh_model_manifests_stable.sh
- opendatahub/scripts/gen-manifests/odh_modelmesh_manifests.sh
- opendatahub/scripts/gen-manifests/odh_modelmesh_manifests_stable.sh
- opendatahub/scripts/gen_copy_new_manifests.sh
- opendatahub/scripts/gen_odh_model_manifests.sh
- opendatahub/scripts/gen_odh_modelmesh_manifests.sh
- opendatahub/scripts/install_odh.sh
ModelServing utilizes the kserve/modelmesh manifest as a base but makes some modifications before using it. However, these modifications require mostly manual intervention. Nevertheless, automating some parts of the process can still be helpful. In this pull request (PR),  scripts and templates have been added to generate manifests for the main/stable branches.
This is not source change so it does not need to test.
> Enhance gen-scripts for new manifests

- opendatahub/odh-manifests/model-mesh/odh-model-controller/manager/manager.yaml
- opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/manager/manager.yaml
Cherry-pick of #115 
- N/A If the PR adds a new container image or updates the tag of an existing image (not build within cpaas), is the corresponding change made in live-builder and cpaas-midstream to add/update the image tag in the operator CSV? Link the PRs if applicable
> [v0.11.0] Add pod anti-affinity to odh-model-controller manifests

- opendatahub/odh-manifests/model-mesh/odh-model-controller/manager/manager.yaml
- opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/manager/manager.yaml
See https://github.com/opendatahub-io/odh-model-controller/pull/51
> Add pod anti-affinity to odh-model-controller manifests

- opendatahub/odh-manifests/model-mesh/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh/odh-modelmesh-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_stable/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_stable/odh-modelmesh-controller/overlays/odh/kustomization.yaml
With the new manifests, it tries to use a new label to explain components but it causes an upgrade fail because the spec.selector in the deployment is immutable.
In order to upgrade properly, I rollback the label.
It does not impact a fresh installation but it will help to upgrade the previous modelmesh component.
It does not need tests because it does not impact to a fresh installation.
> fix RHODS-9627 - rollback label

- opendatahub/odh-manifests/model-mesh/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_stable/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_stable/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/base/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-model-controller/overlays/odh/kustomization.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-model-controller/overlays/odh/odh_model_controller_manager_patch.yaml
- opendatahub/odh-manifests/model-mesh_templates_stable/odh-modelmesh-controller/overlays/odh/kustomization.yaml
Regression issue: 
- https://github.com/opendatahub-io/modelmesh-serving/pull/138
- https://github.com/opendatahub-io/modelmesh-serving/pull/115
It was because the template folder was not updated properly so this pr updated manifests template folder.
It is not needed to test because it does not change sources. 
> update template manifests for fast/stable

- .github/workflows/auto-add-issues-to-project.yaml
This will enable auto adding of all our issues to main ODH board. This will help QE and docs to track all issues going into ODH and RHODS releases.
No code modifications
No need to check the tests, as it is not a code change but a GH action change.
> auto add issues to main odh board

- Dockerfile.develop
- Dockerfile.develop.ci
t):
File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 565, in untar_file
tarfile.data_filter(member.replace(name=fn), location)
AttributeError: module 'tarfile' has no attribute 'data_filter'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 346, in run
requirement_set.prepare_files(finder)
File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 381, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 623, in _prepare_file
session=self.session, …
> fix docker build fail issue

- config/overlays/odh/default/kustomization.yaml
This change is to fix https://issues.redhat.com/browse/RHOAIENG-244. 
Empty string of caBundle in `ValidationWebhookConfiguration` causes cyclic calling of reconcilation for DataScienceCluster controller. With this PR I had removed the empty caBundle string from `ValidationWebhookConfiguration`. Similiar [patch](https://github.com/opendatahub-io/kserve/blob/bb3615b964ed93e715769ee981ffa228ac3a0227/config/default/kustomization.yaml#L225) is already applied in KServe manifest but missing in ModelMesh-Serving.
It should not impact any existing functionalities.
1. Clone the code changes
2. navigate to `modelmesh-serving` folder
3. create manifest
```
kustomize build config/overlays/odh > mm.yaml
```
4. Varify caBundle field should not present in ValidatingWebhookConfiguration resource. …
> Apply patch to remove empty string of caBundle

- config/overlays/odh/default/kustomization.yaml
Cherry-pick https://github.com/opendatahub-io/modelmesh-serving/pull/262
> Cherry-pick: Apply patch to remove empty string of caBundle #262

- Dockerfile.develop
- Dockerfile.develop.ci
fix(test): pins k8s env test to concrete version
Latest one requires go1.22 which is not the version used by prow jobs atm.
> pin envtest version, not using go 1.22 yet

- opendatahub/docs/upstream-code-sync-process.md
This adds a new GitHub issue template which covers synchronization of all ModelMesh related ODH repositories forks with upstream repositories.
Related to https://github.com/opendatahub-io/modelmesh-serving/issues/188
> Add issue template for code synchronization

- config/overlays/odh/quickstart.yaml
Updated the manifest to include requests and limits for the etcd deployment. 
Tested by applying resource quota to the redhat-ods-applications project and viewing which resources did not automatically rollout after applying the rq. 
After finding that the etcd deployment was the only pod that was not automatically redeployed, viewed the metrics for the etcd pod with no changes to find the request boundaries, and then added and deleted multiple ISVC's to find the limit boundaries. 
Here is a copy of the RQ I used:
```
apiVersion: v1
kind: ResourceQuota
metadata:
name: compute-resources
spec:
hard:
pods: "4" 
requests.cpu: 50m 
requests.memory: 96Mi 
limits.cpu: "1" 
limits.memory: 512Mi 
``` 
2 ways to apply -- CLI or UI
1. **Using the CL**I, ensure you are logged into the cluster, and …
> [RHOAIENG-11850] Updated etcd manifest

- config/overlays/odh/quickstart.yaml
Cherry picked the fixes from https://github.com/opendatahub-io/modelmesh-serving/pull/303  to the release branch 0.12.0-rc0
> RHOAIENG-11850: Cherry-pick fix to release-0.12.0-rc0

- config/overlays/odh/quickstart.yaml
Previous resources in https://github.com/opendatahub-io/modelmesh-serving/pull/303 was too low and caused modelmesh deployments to fail. -- this pr made limit and request values higher in the etcd container.
> [RHOAIENG-13816] Updated etcd manifest

- config/overlays/odh/quickstart.yaml
Cherry-picked to fix as the previous resources in https://github.com/opendatahub-io/modelmesh-serving/pull/303 was too low and caused modelmesh deployments to fail. -- this pr made limit and request values higher in the etcd container.
> Cherry-pick the etcd fix to the release branch

- Dockerfile
chore:	Add the go.mod and go.sum files to the builder image, on Konflux the
dependencies were not getting resolved due to the lack of these files.
> [RHOAIENG-11043] - Konflux Build failure for modelmesh-serving component

- config/component_metadata.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-18612
Adding release metadata for modelmesh-serving that will be displayed in Dashboard
Cherry pick of https://github.com/opendatahub-io/modelmesh-serving/pull/312
> [Cherry-pick] from main to release: Add release metadata for MM (#312)

- config/internal/base/deployment.yaml.tmpl
- controllers/testdata/servingruntime_controller.golden
chore:	Update the oauth-proxy to the latest
registry.redhat.io/openshift4/ose-oauth-proxy@sha256:8507daed246d4d367704f7d7193233724acf1072572e1226ca063c066b858ecf
> Update the oauth-proxy to the latest

- config/internal/base/deployment.yaml.tmpl
- controllers/testdata/servingruntime_controller.golden
chore:	Update the oauth-proxy to the latest
registry.redhat.io/openshift4/ose-oauth-proxy@sha256:8507daed246d4d367704f7d7193233724acf1072572e1226ca063c066b858ecf
Cherry-picks: https://github.com/opendatahub-io/modelmesh-serving/pull/315
> [Cherry-pick] Update the oauth-proxy to the latest (#315)

- config/dependencies/fvt.yaml
- config/overlays/odh/quickstart.yaml
- opendatahub/scripts/manifests/fvt/fvt.yaml
chore:	Update etcd and ose-cli images
etcd image updated:
Tested with:
```yaml
spec:
components:
codeflare:
managementState: Removed
dashboard:
managementState: Removed
datasciencepipelines:
managementState: Removed
kserve:
managementState: Removed
serving:
ingressGateway:
certificate:
type: OpenshiftDefaultIngress
managementState: Managed
name: knative-serving
kueue:
managementState: Removed
modelmeshserving:
managementState: Managed
devFlags:
manifests:
- contextDir: config
sourcePath: overlays/odh
uri: "https://github.com/spolti/modelmesh-serving/tarball/model-mesh"
modelregistry:
managementState: Removed
registriesNamespace: rhoai-model-registries
ray:
managementState: Removed
trainingoperator:
managementState: Removed
trustyai:
managementState: Removed
workbenches:
managementState: …
```
> [RHOAIENG-18240] - Update ETCD in ModelMesh

- config/dependencies/fvt.yaml
- config/overlays/odh/quickstart.yaml
- opendatahub/scripts/manifests/fvt/fvt.yaml
chore:	Update etcd and ose-cli images
Cherry-picks: https://github.com/opendatahub-io/modelmesh-serving/pull/313
> [Cherry-pick][RHOAIENG-18240] - Update ETCD in ModelMesh (#313)

- .tekton/odh-modelmesh-serving-controller-push.yaml
Correct the generation of the image:tag path
Modified all tasks within the pipelineSpec to build the full image URLs dynamically using the output-image-base and odh-tag parameters
> Correctly build the image:tag value in the pipelineSpec field

- .tekton/odh-modelmesh-serving-controller-push.yaml
Update Tekton output-image tags to version odh-v2.33
[RHOAIENG-29332]
> Odh v2.32 release

- .tekton/odh-modelmesh-serving-controller-push.yaml
Update Tekton output-image tags to version odh-v2.34
[RHOAIENG-30987]
> Odh v2.33 release
