opendatahub-io/modelmesh-serving

- config/internal/base/deployment.yaml.tmpl
- controllers/modelmesh/modelmesh.go
- controllers/modelmesh/runtime.go
- controllers/service_controller.go
- pkg/mmesh/modelmesh_service.go
- scripts/build_devimage.sh
- scripts/build_docker.sh
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Prototype for oauth config

- manifests/opendatahub/dependencies/fvt.yaml
- manifests/opendatahub/dependencies/quickstart.yaml
- tests/basictests/modelmesh.sh
- tests/resources/modelmesh/serving-runtime.yaml
- tests/resources/modelmesh/triton-inference-service.yaml
- tests/scripts/install.sh
Use RH-based Etcd container
Update image pointer to modh etcd repo
> Update manifests to use RH-built Etcd image

- manifests/opendatahub/manager/manager.yaml
- manifests/opendatahub/overlays/odh-model-controller/rbac/auth_proxy_service.yaml
Add monitoring for modelmesh
MM service objects
metrics port should be exposed
> Change modelmesh deployments to expose metrics port

- manifests/opendatahub/overlays/odh-model-controller/manager/kustomization.yaml
- odh-model-controller/controllers/inferenceservice_route.go
- quickstart/openvino-serving-runtime.yaml
- tests/resources/modelmesh/serving-runtime.yaml
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Update the annotations required for authentication and routes

- OWNERS
Add HumairAK to owners. Longer term we need to revisit the reviewers and approvers instead of having everyone able to approve PRs
cc @HumairAK
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>
> Add Humair to OWNERS

- config/runtimes/kustomization.yaml
Related to https://github.com/opendatahub-io/odh-manifests/pull/713
> Update kustomization for OVMS 2022.3

- .github/workflows/build-and-push.yml
- .github/workflows/run-fvt.yml
- Dockerfile
- Dockerfile.develop
- README.md
- config/default/config-defaults.yaml
- config/dependencies/quickstart.yaml
- config/manager/manager.yaml
- config/runtimes/kustomization.yaml
- config/runtimes/torchserve-0.x.yaml
- controllers/modelmesh/cluster_config.go
- controllers/servingruntime_controller_test.go
- controllers/testdata/servingruntime_controller.golden
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- docs/runtimes/README.md
- docs/runtimes/mlserver_custom.md
- fvt/predictor/predictor_suite_test.go
- fvt/scaleToZero/scaleToZero_suite_test.go
- go.mod
- go.sum
- pkg/config/config.go
- scripts/install.sh
- scripts/setup_user_namespaces.sh
Jira: [RHODS-6131](https://issues.redhat.com//browse/RHODS-6131)
> Sync upstream

- version
> update version information for master

- .github/pull_request_template.md
> Add PR checklist

- OWNERS
Updating the OWNERS section
No modification that needs testing
> Removed Anish from Owners per request

- opendatahub/scripts/repeat_fvt.sh
Simple script bug 
Move fvt_result line 
It can get the right result from fvt.
It does not change any sources
==> it does not need this
> fix scripts for e2e

- opendatahub/scripts/download_images_on_nodes.sh
- opendatahub/scripts/repeat_fvt.sh
> Scripts fix

- opendatahub/docs/makefile-cheatsheet.md
- opendatahub/docs/manifests-management.md
Makefile and scripts are updated recently but the docs are not updated properly so it updates the docs
This PR does not need unit/fvt test.
> opendatahub docs are updated

- opendatahub/quickstart/common_docs/modelmesh-install.md
Fixing Quick start guide to install ModelMesh
> Fix instruction sequence in ModelMesh Installation guide

- opendatahub/quickstart/pvc/deploy.sh
> Fix the script of pvc #177

- opendatahub/scripts/download_images_on_nodes.sh
- opendatahub/scripts/utils.sh
- scripts/download-images-on-nodes.sh
Fix max-retries feature for odh-manifests and also add the same feature for fvt.
This is not needed to test  because it is not source code and it will be executed in openshift-ci everytime
> add max-retries for downloading-images

- opendatahub/scripts/README.md
This PR format README.md file but it is for triggering openshift-ci.
This is not needed to test because it does not change source.
> formatting README.md

- opendatahub/manifests/base/params.env
- opendatahub/manifests/dependencies/quickstart.yaml
- opendatahub/manifests/manager/kustomization.yaml
- opendatahub/manifests/manager/manager.yaml
- opendatahub/manifests/overlays/odh/kustomization.yaml
> update manifests from odh-manifests/master

- opendatahub/manifests/base/kustomization.yaml
> fix mesh params map

- opendatahub/manifests/base/kustomization.yaml
> remove env ref to odh model controller

- .github/workflows/auto-add-issues-to-project.yaml
Adding our board to add-issue-to-board automation.
> add mlserving board as well

- config/overlays/odh/params.env
Version v0.11.1.2 will be the similar as v0.11.1.1. Only odh-model-controller has updates.
> Update references to images

- config/overlays/odh/params.env
> Prepare for ODH release and update the tag to 0.11.1.3

- config/overlays/odh/quickstart.yaml
https://issues.redhat.com/browse/RHOAIENG-1005
> increase etcd resources

- .github/workflows/create-release.yml
What this PR does / why we need it:
Automate ODH Release Process for Kserve repos
Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #[RHOAIENG-2732](https://issues.redhat.com/browse/RHOAIENG-2732)
> Modify Regular Expression for the support of suffix with latest/fast

- .github/workflows/create-release.yml
- config/overlays/odh/params.env
Cherry-pick of:
* #289 
* #290 
Also, update `params.env` file to use `v*` tags compatible with the release workflow.
> Prepare v0.12.0-rc0 branch for release

- Dockerfile
- Dockerfile.develop
- Dockerfile.develop.ci
Cherr-picks https://github.com/opendatahub-io/modelmesh-serving/pull/292 
> [RHOAIENG-7291] - [Set latest Tag] OpenDataHub - Modelmesh

- config/crd/bases/serving.kserve.io_inferenceservices.yaml
- config/crd/bases/serving.kserve.io_servingruntimes.yaml
need the latest api so need to update some CRD to the latest
> update crd to the latest(0.14) of kserve

- OWNERS
user andresllh requires approver and reviewer permissions for PRs in this repo
adding andresllh as approver and reviewer in OWNERS file
user andresllh will have approver and reviewer permissions for PRs in this repo
> adding andresllh as approver and reviewer in OWNERS file

- .github/workflows/fvt-base.yml
- .pre-commit-config.yaml
- Dockerfile
- Dockerfile.develop
- Dockerfile.develop.ci
- Makefile
- controllers/modelmesh/cluster_config.go
- controllers/modelmesh/modelmesh.go
- controllers/modelmesh/proxy.go
- controllers/servingruntime_controller.go
- controllers/testdata/servingruntime_controller.golden
- fvt/fvtclient.go
- fvt/globals.go
- fvt/predictor/predictor_suite_test.go
- fvt/predictor/predictor_test.go
- go.mod
- pkg/config/config.go
Cherry-picks:
- 5417f848419fd5c1fbd0c97249e8876f00567843
- 047fdd206f704bd3e95488e9dbb1401f9d11c03e
- bca084254a0af2f280e4267301bbe6ba2ed4b9c7
> [Cherry-pick] - cherry-pick needed commits to release branch

- Dockerfile.develop
> use unversioned python

- Dockerfile.develop
> use dnf instead microdnf

- Dockerfile.develop
- Dockerfile.develop.ci
- go.mod
https://issues.redhat.com/browse/RHOAIENG-24155 
> update to go 1.23

- .tekton/odh-modelmesh-serving-controller-push.yaml
Fix the build-develop-container step
[RHOAIENG-29262](https://issues.redhat.com/browse/RHOAIENG-29262)
> Remove the extra image from build-develop-container
